apiVersion: v1
kind: Secret
metadata:
  name: microb-postgres-secret # по этому имени мы будем обращаться к секрету
  namespace: fullstack
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/microb
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres
