apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fullstack
  name: backend-deployment-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server1
  template:
    metadata:
      labels:
        app: server1
    spec:
      containers:
        - name: server1
          image: andreyrf98/backend-one-image:0.0.2
          ports:
            - containerPort: 8081
              name: web
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: microb-postgres-secret
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: microb-postgres-secret
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microb-postgres-secret
                  key: SPRING_DATASOURCE_PASSWORD
