apiVersion: v1
kind: Service
metadata:
  name: backend-svc-1
  namespace: fullstack
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.10.244"
spec:
  type: LoadBalancer
  selector:
    app: server1
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
