apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fullstack
  name: backend-deployment-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server2
  template:
    metadata:
      labels:
        app: server2
    spec:
      containers:
        - name: server2
          image: andreyrf98/backend-two-image:0.0.1
          ports:
            - containerPort: 8082
              name: web
