apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: fullstack
spec:
  ingressClassName: nginx
  rules:
    - host: api.playground.zaikin.ru
      http:
        paths:
          - path: /products
            pathType: Prefix
            backend:
              service:
                name: backend-svc-1
                port:
                  number: 8081
          - path: /welcome
            pathType: Prefix
            backend:
              service:
                name: backend-svc-2
                port:
                  number: 8082
